### ISSUE TITLE
4.8.0.80新版本前端菜单样式新增，有多了个碍眼的滑轮

### ISSUE THREAD

**Issue by JsaRut** [Nolovenodie/emby-crx#49]
![image](https://github.com/Nolovenodie/emby-crx/assets/89496854/f4b42262-cc9c-413d-bdf4-2f9b964f4bca)

**Comment by noir1216** [comment]
同求更新
不过今天Emby刚更新了4.8.1.0
说是修复了一系列bug
建议作者直接适配4.8.1.0

**Comment by jqtmviyu** [comment]
4.9.0.26

style.css 更改 54行下面添加 `width: 100%;`

```css
.view:not(.hide) .section0 .cardText button {
	text-decoration: none;
        width: 100%;
}
```
